---
name: Create packages and test installation

on:
  pull_request:

jobs:
  # XXX done outside of the build matrix due to different container name
  build-centos7:
    strategy:
      fail-fast: false
      matrix:
        rpm-name:
          [emi-bdii-site, emi-bdii-top, emi-resource-information-service]
    name: Build ${{ matrix.rpm-name }} CentOS 7 RPMs
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build yum-utils rpmlint
          cd ${{ matrix.rpm-name }}
          yum-builddep -y ${{ matrix.rpm-name }}.spec
      - name: Build rpm
        run: |
          cd ${{ matrix.rpm-name }}
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.el7.noarch.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms7-${{ matrix.rpm-name }}
          path: |
            ${{ matrix.rpm-name }}/build/RPMS/noarch/${{ matrix.rpm-name }}-*.el7.noarch.rpm

  # Use a matrix for AlmaLinux versions
  build:
    strategy:
      fail-fast: false
      matrix:
        almalinux-version: [8, 9]
        rpm-name:
          [emi-bdii-site, emi-bdii-top, emi-resource-information-service]
    name: Build ${{ matrix.rpm-name }} AlmaLinux ${{ matrix.almalinux-version }} RPMs
    runs-on: ubuntu-latest
    container: almalinux:${{ matrix.almalinux-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build yum-utils rpmlint
          cd ${{ matrix.rpm-name }}
          yum-builddep -y ${{ matrix.rpm-name }}.spec
      - name: Build rpm
        run: |
          cd ${{ matrix.rpm-name }}
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.el${{ matrix.almalinux-version }}.noarch.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms${{ matrix.almalinux-version }}-${{ matrix.rpm-name }}
          path: |
            ${{ matrix.rpm-name }}/build/RPMS/noarch/${{ matrix.rpm-name }}-*.el${{ matrix.almalinux-version }}.noarch.rpm

  install-centos7:
    strategy:
      fail-fast: false
      matrix:
        rpm-name:
          [emi-bdii-site, emi-bdii-top, emi-resource-information-service]
    name: Install ${{ matrix.rpm-name }} CentOS 7 RPMs
    needs: build-centos7
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms7-${{ matrix.rpm-name }}
      - name: Install generated RPMs
        run: |
          yum install -y http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm
          yum localinstall -y ${{ matrix.rpm-name }}-*.el7.noarch.rpm

  # FIXME: openldap-servers is in CentOS 8 Stream Powertools, but not in AlmaLinux PowerTools
  # See https://bugs.almalinux.org/view.php?id=222
  # Currently instaling using the package from devel repository
  # See https://bugs.almalinux.org/view.php?id=100
  # https://repo.almalinux.org/almalinux/8/devel/x86_64/os/Packages/
  almalinux8-install:
    strategy:
      fail-fast: false
      matrix:
        rpm-name:
          [emi-bdii-site, emi-bdii-top, emi-resource-information-service]
    name: Install ${{ matrix.rpm-name }} AlmaLinux 8 RPMs
    needs: build
    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms8-${{ matrix.rpm-name }}
      - name: Install generated RPMs
        run: |
          yum install -y https://repo.almalinux.org/almalinux/8/devel/x86_64/os/Packages/openldap-servers-2.4.46-18.el8.x86_64.rpm
          yum localinstall -y ${{ matrix.rpm-name }}-*.el8.noarch.rpm

  # XXX Dependencies from EPEL: openldap-servers
  almalinux9-install:
    strategy:
      fail-fast: false
      matrix:
        rpm-name:
          [emi-bdii-site, emi-bdii-top, emi-resource-information-service]
    name: Install ${{ matrix.rpm-name }} AlmaLinux 9 RPMs
    needs: build
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms9-${{ matrix.rpm-name }}
      - name: Install generated RPMs
        run: |
          yum install -y epel-release
          yum localinstall -y ${{ matrix.rpm-name }}-*.el9.noarch.rpm
