---
# When a tag is created
# - create a new release from the tag
# - build and attach packages to the release
name: Create packages and release

on:
  push:
    tags:
      - "v*"

jobs:
  centos7:
    strategy:
      matrix:
        rpm-name:
          [emi-bdii-site, emi-bdii-top, emi-resource-information-service]
    name: Build ${{ matrix.rpm-name }} CentOS 7 RPMs
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build yum-utils
          cd ${{ matrix.rpm-name }}
          yum-builddep -y ${{ matrix.rpm-name }}.spec
      - name: Build rpm
        run: |
          cd ${{ matrix.rpm-name }}
          make clean rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms7-${{ matrix.rpm-name }}
          path: |
            ${{ matrix.rpm-name }}/build/RPMS/noarch/${{ matrix.rpm-name }}-*.el7.noarch.rpm
            ${{ matrix.rpm-name }}/build/SRPMS/${{ matrix.rpm-name }}-*.el7.src.rpm

  # Use a matrix for AlmaLinux versions
  build:
    strategy:
      matrix:
        almalinux-version: [8, 9]
        rpm-name:
          [emi-bdii-site, emi-bdii-top, emi-resource-information-service]
    name: Build ${{ matrix.rpm-name }} AlmaLinux ${{ matrix.almalinux-version }} RPMs
    runs-on: ubuntu-latest
    container: almalinux:${{ matrix.almalinux-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build yum-utils
          cd ${{ matrix.rpm-name }}
          yum-builddep -y ${{ matrix.rpm-name }}.spec
      - name: Build rpm
        run: |
          cd ${{ matrix.rpm-name }}
          make clean rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms${{ matrix.almalinux-version }}-${{ matrix.rpm-name }}
          path: |
            ${{ matrix.rpm-name }}/build/RPMS/noarch/${{ matrix.rpm-name }}-*.el${{ matrix.almalinux-version }}.noarch.rpm
            ${{ matrix.rpm-name }}/build/SRPMS/${{ matrix.rpm-name }}-*.el${{ matrix.almalinux-version }}.src.rpm

  release7:
    strategy:
      matrix:
        rpm-name:
          [emi-bdii-site, emi-bdii-top, emi-resource-information-service]
    name: Upload ${{ matrix.rpm-name }} CentOS 7 release artefacts
    needs: centos7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms7-${{ matrix.rpm-name }}
      - name: Find package name
        id: package_name_centos7
        run: |
          rpm_path=$(find . -name '${{ matrix.rpm-name }}-*.el7.noarch.rpm')
          src_path=$(find . -name '${{ matrix.rpm-name }}-*.el7.src.rpm')
          echo "rpm_path=${rpm_path}" >> "$GITHUB_OUTPUT"
          echo "src_path=${src_path}" >> "$GITHUB_OUTPUT"
      - name: Attach CentOS 7 RPMs to the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          files: |
            ${{ steps.package_name_centos7.outputs.rpm_path }}
            ${{ steps.package_name_centos7.outputs.src_path }}

  release8:
    strategy:
      matrix:
        rpm-name:
          [emi-bdii-site, emi-bdii-top, emi-resource-information-service]
    name: Upload ${{ matrix.rpm-name }} AlmaLinux 8 release artefacts
    needs: almalinux8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms8-${{ matrix.rpm-name }}
      - name: Find package name
        id: package_name_almalinux8
        run: |
          rpm_path=$(find . -name '${{ matrix.rpm-name }}-*.el8.noarch.rpm')
          src_path=$(find . -name '${{ matrix.rpm-name }}-*.el8.src.rpm')
          echo "rpm_path=${rpm_path}" >> "$GITHUB_OUTPUT"
          echo "src_path=${src_path}" >> "$GITHUB_OUTPUT"
      - name: Attach AlmaLinux 8 RPMs to the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          files: |
            ${{ steps.package_name_almalinux8.outputs.rpm_path }}
            ${{ steps.package_name_almalinux8.outputs.src_path }}

  release9:
    strategy:
      matrix:
        rpm-name:
          [emi-bdii-site, emi-bdii-top, emi-resource-information-service]
    name: Upload ${{ matrix.rpm-name }} CentOS Stream 9 release artefacts
    needs: almalinux9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms9-${{ matrix.rpm-name }}
      - name: Find package name
        id: package_name_almalinux9
        run: |
          rpm_path=$(find . -name '${{ matrix.rpm-name }}-*.el9.noarch.rpm')
          src_path=$(find . -name '${{ matrix.rpm-name }}-*.el9.src.rpm')
          echo "rpm_path=${rpm_path}" >> "$GITHUB_OUTPUT"
          echo "src_path=${src_path}" >> "$GITHUB_OUTPUT"
      - name: Attach AlmaLinux 9 RPMs to the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          files: |
            ${{ steps.package_name_almalinux9.outputs.rpm_path }}
            ${{ steps.package_name_almalinux9.outputs.src_path }}
